### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by justquick** [RaymiiOrg/confluence-python-cli#3]
When trying to access a wikiurl with https instead of http I get this error:

```
$ python confluence.py --wikiurl="https://confluence.mydomain.com/" ...
Traceback (most recent call last):
  File "confluence.py", line 427, in <module>
    main()
  File "confluence.py", line 424, in main
    server = Connect(args)
  File "confluence.py", line 296, in Connect
    token = ConfluenceAuth(xml_server,args.username,args.password).login()
  File "confluence.py", line 174, in login
    self.token = self.server.confluence2.login(self.username, self.password)
  File "/home/nfs/jquick/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/home/nfs/jquick/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/home/nfs/jquick/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/nfs/jquick/lib/python2.7/xmlrpclib.py", line 1284, in single_request
    h = self.make_connection(host)
  File "/home/nfs/jquick/lib/python2.7/xmlrpclib.py", line 1492, in make_connection
    "your version of httplib doesn't support HTTPS"
NotImplementedError: your version of httplib doesn't support HTTPS
```

Occurs with Python v2.7.8. Is there another version of httplib that I should try instead?

**Comment by jwarlander** [comment]
I've also only used HTTPS, and it works flawlessly. I notice that you're using a locally installed Python in your home directory; did you have the necessary prerequisites for SSL support enabled when you compiled?

For Ubuntu, for example, you'd need to..

    sudo apt-get install libssl-dev
